### ISSUE TITLE
Errors during installation [Ubuntu 22.04 x86_64]

### ISSUE THREAD

**Issue by zebede22** [nahuhh/basicswap-bash#2]
OS: Ubuntu Server 22.04
Python 3.10.12
Kernel: Linux 5.15.0-119-generic

```bash
git clone https://github.com/nahuhh/basicswap-bash
cd basicswap-bash && ./install.sh
```

Output with errors:

```bash
************************************************************************************************************************************************************************
                                                                         BasicSwapDEX Installer
************************************************************************************************************************************************************************
Detected Debian

...

[1] Tor ON (requires sudo)
[2] Tor OFF

Select an option: [1|2] 1

BasicSwapDEX will use Tor

[1] New Install (default)
[2] Restore from Particl Seed

Select an option: [1|2] 1

Installing BasicSwapDEX

[1] Connect to a Monero node
[2] Allow BasicSwapDEX to run a Monero node (+70GB)

Select an option [1|2]: 1
Enter Address of Monero node [example: 192.168.1.123] 127.0.0.1
Enter RPC Port for the Monero node [example: 18081] 18089

Successfully connected to the XMR node @ 127.0.0.1:18089

Installing BasicSwapDEX
Press Enter to continue, or CTRL-C to exit.

...

cat: /home/user/.xsessionrc: No such file or directory # <--- first error

...
# >>> another error
mv: cannot move './coincurve-anonswap/coincurve-anonswap_v0.2/.' to './coincurve-anonswap/.': Device or resource busy
mv: cannot move './coincurve-anonswap/coincurve-anonswap_v0.2/..' to './coincurve-anonswap/..': Device or resource busy

...

Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 PySocks-1.7.1 basicswap-0.13.4 greenlet-3.0.3 pycryptodome-3.20.0 python-gnupg-0.5.2 pyzmq-26.2.0 sqlalchemy-1.4.39 wheel-0.44.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0  10182      0 --:--:-- --:--:-- --:--:-- 14000
parse error: Invalid numeric literal at line 1, column 32
Traceback (most recent call last):
  File "/home/user/coinswaps/venv/bin/basicswap-prepare", line 33, in <module>
    sys.exit(load_entry_point('basicswap==0.13.4', 'console_scripts', 'basicswap-prepare')())
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/bin/basicswap_prepare.py", line 1684, in main
    xmr_restore_height = int(s[1])
ValueError: invalid literal for int() with base 10: ''


INFO:root:BasicSwap prepare script 0.13.4

INFO:root:Python version: 3.10.12
INFO:root:Data dir: /home/user/coinswaps
INFO:root:Bin dir: /home/user/coinswaps/bin
INFO:root:Chain: mainnet
INFO:root:WALLET_ENCRYPTION_PWD is not set
INFO:root:Enabling TOR

```

When I try to start it anyway: `basicswap-bash`

```
Python 3.10.12
INFO:root:Using datadir: /home/user/coinswaps
INFO:root:Chain: mainnet
INFO:root:basicswap-run, version: 0.13.4


Traceback (most recent call last):
  File "/home/user/coinswaps/venv/bin/basicswap-run", line 8, in <module>
    sys.exit(main())
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/bin/basicswap_run.py", line 443, in main
    runClient(fp, data_dir, chain, start_only_coins)
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/bin/basicswap_run.py", line 185, in runClient
    raise ValueError('Settings file not found: ' + str(settings_path))
ValueError: Settings file not found: /home/user/coinswaps/basicswap.json
```

**Comment by zebede22** [comment]
I think problem is that `CURRENT_XMR_HEIGHT=$(curl https://localmonero.co/blocks/api/get_stats | jq .height)` doesn't work.
when I run `curl https://localmonero.co/blocks/api/get_stats` it timesout, I can't even access it via a browser

**Comment by nahuhh** [comment]
Localmonero blocks is down, let me check and update script

**Comment by nahuhh** [comment]
might be a bug with using localhost.

try entering your local ip (192.168.x.x) instead of 127.0.0.1

**Comment by zebede22** [comment]
> might be a bug with using localhost.
> 
> try entering your local ip (192.168.x.x) instead of 127.0.0.1
> 
> or if the the port isnt bound to the lan interface, try `localhost`

I tried public IP and `localhost` but still same errors

**Comment by nahuhh** [comment]
Is your node accessible over that ip?

curl http://localhost:18089/get_info

**Comment by zebede22** [comment]
```
<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>
```
My node using user:pass for auth, I guess that's reason.
Is there an option to specify one?

**Comment by nahuhh** [comment]
Run this:
```
git clone https://github.com/nahuhh/basicswap-bash
cd basicswap-bash
```

then add these lines near the top of `bsx/setup.sh`
```
XMR_RPC_USER=yourusername
XMR_RPC_PWD=yourpassword
```

then run
```
./install
```

**Comment by zebede22** [comment]
I already managed to start it properly via using a public node, how can I delete/uninstall whole thing?
is deleting ~/.local/bin/bsx* and ~/.local/bin/basicswap-bash enough?

**Comment by nahuhh** [comment]
you done have to delete, you can edit it to use your own node

edit `~/coinswaps/basicswap.json`
go to the `monero` section

add 2 lines

```
"rpcuser": "youruser",
"rpcpassword": "yourpassword",
```

if youd like to delete for any reason, just need to delete the `coinswaps` folder

**Comment by zebede22** [comment]
I tried
XMR_RPC_USER=yourusername
XMR_RPC_PWD=yourpassword

but still getting same error

**Comment by nahuhh** [comment]
try setting up with remote node, then editing basicswap.json as above

**Comment by zebede22** [comment]
Worked
