### ISSUE TITLE
Unable to add Litecoin

### ISSUE THREAD

**Issue by zebede22** [nahuhh/basicswap-bash#3]
Error:
```bash
INFO:root:Starting node /home/user/coinswaps/bin/particl/particld -datadir=/home/user/coinswaps/particl
2024-09-07 20:41:22 DEBUG : Reading PART rpc credentials from auth cookie /home/user/coinswaps/particl/.cookie
2024-09-07 20:41:22 WARNING : Error, iteration 0: [Errno 2] No such file or directory: '/home/user/coinswaps/particl/particl.pid'
2024-09-07 20:41:22 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 1 second/s, 1/21.
2024-09-07 20:41:23 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 2 second/s, 2/21.
2024-09-07 20:41:26 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 3 second/s, 3/21.
2024-09-07 20:41:29 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 4 second/s, 4/21.
2024-09-07 20:41:33 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 5 second/s, 5/21.
2024-09-07 20:41:38 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 6 second/s, 6/21.
2024-09-07 20:41:44 INFO : unlockWallet - PART
2024-09-07 20:41:44 INFO : Finalise
INFO:root:Interrupting 1126276
Traceback (most recent call last):
  File "/home/user/coinswaps/venv/bin/basicswap-prepare", line 8, in <module>
    sys.exit(main())
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/bin/basicswap_prepare.py", line 2086, in main
    initialise_wallets(None, {add_coin, }, data_dir, settings, chain, use_tor_proxy)
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/bin/basicswap_prepare.py", line 1466, in initialise_wallets
    swap_client.ci(c).unlockWallet(WALLET_ENCRYPTION_PWD)
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/basicswap/interface/btc.py", line 1412, in unlockWallet
    self.rpc_wallet('walletpassphrase', [password, xxxxxxxxxx])
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/basicswap/rpc.py", line 149, in rpc_func
    return callrpc(port, auth, method, params, wallet if wallet_override is None else wallet_override, host)
  File "/home/user/coinswaps/venv/lib/python3.10/site-packages/basicswap/rpc.py", line 100, in callrpc
    raise ValueError('RPC error ' + str(r['error']))
ValueError: RPC error {'code': -15, 'message': 'Error: running with an unencrypted wallet, but walletpassphrase was called.'}
```

**Comment by nahuhh** [comment]
If you have a password set: Basicswap has to be shut down to add coins

if you dont have a password set: select "no password" option when adding

**Comment by zebede22** [comment]
Even though I had password set, the adding coin worked when I said that there is no password

**Comment by zebede22** [comment]
BTW, that was not my password on the log

**Comment by nahuhh** [comment]
> Even though I had password set, the adding coin worked when I said that there is no password

The wallet was already unlocked.

in future, only add coins when bsx is closed
